import type { Metadata } from "next"
import { Fira_Code } from "next/font/google"
import { ThemeProvider } from "@/context/theme-provider"
import { DotBackground } from "@/components/dot-background"
import { cn } from "@/lib/utils"
import "./globals.css"

const firaCode = Fira_Code({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={cn(firaCode.className, "min-h-dvh")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <DotBackground>
            {children}
          </DotBackground>
        </ThemeProvider>
      </body>
    </html>
  )
}
